name: gh_build_publish
 
on:
  workflow_dispatch:

permissions:
  id-token: write 
  contents: read
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Register Build Artifact
        uses: cloudbees-io-gha/register-build-artifact@v3
        with:
          name: "demo-go-service"
          version: "tagGha"
          url: "020229604682.dkr.ecr.us-east-1.amazonaws.com/throwaway/actions/vulnerable-image:tagGha"
          cloudbees-url: "https://api.saas-preprod.beescloud.com"      
